name: OrangeFox - Build Ctapchuk [Self-hosted]

# Credits to:
# https://github.com/TeamWin
# https://gitlab.com/OrangeFox
# https://github.com/azwhikaru for Recovery Builder Template
# And all Contributors in every repositories I used

on:
  workflow_dispatch:
    inputs:
      DEVICE_TREE:
        description: 'Custom Recovery Tree'
        required: true
        default: 'https://github.com/marat2509/twrp_device_xiaomi_sweet_k6a'
      DEVICE_TREE_BRANCH:
        description: 'Custom Recovery Tree Branch'
        required: true
        default: 'fox_12.1'
      DEVICE_PATH:
        description: 'Specify your device path.'
        required: true
        default: 'device/xiaomi/sweet_k6a'
      DEVICE_NAME:
        description: 'Specify your Device Codename.'
        required: true
        default: 'sweet_k6a'
      BUILD_TARGET:
        description: 'Specify your Build Target'
        required: true
        default: 'recovery'
        type: choice
        options:
        - boot
        - recovery
        - vendorboot
      DEBUG_ENABLED:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
jobs:
  build:
    name: Build
    runs-on: self-hosted
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
              
    - name: Clean-up
      uses: rokibhasansagar/slimhub_actions@main

    - name: Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12
      
    - name: Build Environment
      run: |
        sudo apt install aria2 -y
        git clone https://gitlab.com/OrangeFox/misc/scripts
        cd scripts
        sudo bash setup/android_build_env.sh
      
    - name: Set-up Manifest
      run: |
        cd ${GITHUB_WORKSPACE}
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git clone https://gitlab.com/OrangeFox/sync.git
        cd sync
        ./orangefox_sync.sh --branch 12.1 --path ${GITHUB_WORKSPACE}/OrangeFox
        cd ${GITHUB_WORKSPACE}/OrangeFox
        rm -rf bootable/recovery && git clone -b fox_12.1 https://github.com/Ctapchuk/android_bootable_recovery-OFRP bootable/recovery
        # rm -rf vendor/recovery && git clone -b fox_12.1 https://github.com/Ctapchuk/android_vendor_ofrp vendor/recovery
        rm -rf build/make && git clone -b android-12.1 https://github.com/Ctapchuk/android_build_ofrp build/make

    - name: Clone Device Tree
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox
        git clone ${{ github.event.inputs.DEVICE_TREE }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}

    - name: Building OrangeFox
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox
        set +e
        source build/envsetup.sh
        set -e
        lunch twrp_${{ github.event.inputs.DEVICE_NAME }}-eng && make clean && mka adbd ${{ github.event.inputs.BUILD_TARGET }}image

    - name: Set Build Date # For Build Date Info, currently using Asia/Manila
      run: |
        echo "BUILD_DATE=$(TZ=Europe/Minsk date +%Y%m%d)" >> $GITHUB_ENV

    - name: Check if Recovery Exist
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox
        if [ -f out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.img ]; then
            echo "CHECK_IMG_IS_OK=true" >> $GITHUB_ENV
        else
            echo "Recovery out directory is empty."
        fi
        if [ -f out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.zip ]; then
            echo "CHECK_ZIP_IS_OK=true" >> $GITHUB_ENV
        else
            echo "Recovery out directory is empty."
        fi

    - name: Generate job summary
      run: |
        {
          echo "| Recovery tree | Recovery base |"
          echo "| :---: | :---: |"
          echo "| $(git -C $GITHUB_WORKSPACE/OrangeFox/${{ github.event.inputs.DEVICE_PATH }} rev-parse --short origin/$(git -C $GITHUB_WORKSPACE/OrangeFox/${{ github.event.inputs.DEVICE_PATH }} rev-parse --abbrev-ref HEAD)) | $(git -C $GITHUB_WORKSPACE/OrangeFox/bootable/recovery rev-parse --short origin/$(git -C $GITHUB_WORKSPACE/OrangeFox/bootable/recovery rev-parse --abbrev-ref HEAD)) |"
        } >> $GITHUB_STEP_SUMMARY

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.DEBUG_ENABLED }}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        path: |
          OrangeFox/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.img
          OrangeFox/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.zip
        name: recovery
